"""foundation

Revision ID: d43689520030
Revises:
"""
import sqlalchemy as sa

from alembic import op

revision = 'd43689520030'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('origin', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=512), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('providers',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('credential_configured', sa.Boolean(), nullable=False),
    sa.Column('connection_status', sa.String(length=40), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('policy_links', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('dataset_versions',
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('category_inventory', sa.JSON(), nullable=False),
    sa.Column('import_schema_version', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'version')
    )
    op.create_table('model_snapshots',
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('endpoint_family', sa.String(length=80), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('supported_parameters', sa.JSON(), nullable=False),
    sa.Column('pricing_evidence', sa.JSON(), nullable=False),
    sa.Column('pricing_source', sa.String(length=512), nullable=True),
    sa.Column('pricing_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pricing_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_version', sa.JSON(), nullable=False),
    sa.Column('availability', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_account_states',
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quota_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quota_source', sa.String(length=512), nullable=True),
    sa.Column('request_day', sa.String(length=10), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id')
    )
    op.create_table('provider_calls',
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('call_kind', sa.String(length=40), nullable=False),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_items',
    sa.Column('dataset_version_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('task_type', sa.String(length=80), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('choices', sa.JSON(), nullable=True),
    sa.Column('reference_answers', sa.JSON(), nullable=False),
    sa.Column('scoring_config', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=512), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_version_id', 'external_id')
    )
    op.create_table('experiments',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('pause_reason', sa.String(length=80), nullable=True),
    sa.Column('config_schema_version', sa.String(length=40), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('config_sha256', sa.String(length=64), nullable=True),
    sa.Column('provenance_mode', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiment_events',
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiment_models',
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('model_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['model_snapshot_id'], ['model_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id', 'slot')
    )
    op.create_table('generation_jobs',
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('model_slot', sa.Integer(), nullable=False),
    sa.Column('dataset_item_id', sa.Integer(), nullable=False),
    sa.Column('repetition', sa.Integer(), nullable=False),
    sa.Column('variant', sa.String(length=80), nullable=False),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('next_eligible_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_owner', sa.String(length=120), nullable=True),
    sa.Column('lease_token', sa.String(length=120), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_item_id'], ['dataset_items.id'], ),
    sa.ForeignKeyConstraint(['experiment_id', 'model_slot'], ['experiment_models.experiment_id', 'experiment_models.slot'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id', 'model_slot', 'dataset_item_id', 'repetition', 'variant')
    )
    op.create_table('review_assignments',
    sa.Column('opaque_id', sa.String(length=120), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('dataset_item_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=40), nullable=False),
    sa.Column('evaluator_label', sa.String(length=120), nullable=False),
    sa.Column('presentation', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_item_id'], ['dataset_items.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opaque_id')
    )
    op.create_table('pairwise_votes',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_label', sa.String(length=120), nullable=False),
    sa.Column('rubric_version', sa.String(length=40), nullable=False),
    sa.Column('choice', sa.String(length=40), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['review_assignments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'evaluator_label', 'rubric_version')
    )
    op.create_table('request_attempts',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('provider_response_id', sa.String(length=255), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('retry_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eligibility_evidence', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'attempt_number')
    )
    op.create_table('model_responses',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('returned_identity', sa.String(length=255), nullable=True),
    sa.Column('finish_reason', sa.String(length=80), nullable=True),
    sa.Column('usage', sa.JSON(), nullable=True),
    sa.Column('safe_metadata', sa.JSON(), nullable=False),
    sa.Column('identity_mismatch', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['request_attempts.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('human_ratings',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_label', sa.String(length=120), nullable=False),
    sa.Column('rubric_version', sa.String(length=40), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['review_assignments.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['model_responses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id', 'evaluator_label', 'rubric_version')
    )
    op.create_table('metric_results',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=80), nullable=False),
    sa.Column('scorer_version', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Double(), nullable=True),
    sa.Column('normalized_answer', sa.Text(), nullable=True),
    sa.Column('parse_status', sa.String(length=40), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['model_responses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id', 'metric', 'scorer_version')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metric_results')
    op.drop_table('human_ratings')
    op.drop_table('model_responses')
    op.drop_table('request_attempts')
    op.drop_table('pairwise_votes')
    op.drop_table('review_assignments')
    op.drop_table('generation_jobs')
    op.drop_table('experiment_models')
    op.drop_table('experiment_events')
    op.drop_table('experiments')
    op.drop_table('dataset_items')
    op.drop_table('provider_calls')
    op.drop_table('provider_account_states')
    op.drop_table('model_snapshots')
    op.drop_table('dataset_versions')
    op.drop_table('providers')
    op.drop_table('datasets')
    # ### end Alembic commands ###
